version: 2

sources:
  - name: olist
    schema: public
    tables:
      - name: orders
      - name: order_items
      - name: customers
      - name: products
      - name: sellers
      - name: order_reviews
      - name: order_payments
      - name: product_category_name_translation
